version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build: .
    command: rails server -b '0.0.0.0'
    volumes:
      - .:/sfnotebook
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_NAME: sfnotebook
      DATABASE_USER_NAME: postgres
      DATABASE_PASSWORD: postgres
